package in.muktashastra.core.persistence.annotation;

import in.muktashastra.core.persistence.util.JavaConversionType;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface DatabaseColumn {
    String name();
    JavaConversionType javaConversionType();
    boolean primaryKey() default false;
    boolean statusColum() default false;
    boolean nullable() default true;
    boolean autoGenerated() default false;
    int indexSequenceNumber() default 0;
}
