package in.muktashastra.core.persistence.relationalstore.metadata;

import in.muktashastra.core.persistence.util.JavaConversionType;

import java.lang.reflect.Field;

record FieldMetadata(Field field, String columnName, JavaConversionType javaConversionType, boolean nullable, boolean autoGenerated, boolean primaryKey, boolean statusColum, int indexSequenceNumber) {}
