name: Release Library

on:
  push:
    tags:
      - 'v*'   # trigger when you push a tag like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          server-id: github # matches <id> in settings.xml
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: mvn -B clean install

      - name: Deploy to GitHub Packages
        run: mvn -B deploy
